name: Docker Build, Push, and Save as Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      id: docker_build
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/book-bot:latest

    - name: Save Docker image as artifact
      run: |
        docker save ${{ secrets.DOCKER_USERNAME }}/book-bot:latest | gzip > book-bot-image.tar.gz
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: book-bot-image
        path: book-bot-image.tar.gz
